// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwcrchjjzwngysxdhoqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Y3JjaGpqenduZ3lzeGRob3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTUwNzIsImV4cCI6MjA3NTE3MTA3Mn0.ctMTFVTKnldq7bwhVhkpFIZRLrw5ogDrbf6YRjL6X2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});